# Generated by Django 4.0 on 2022-02-05 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_post_dislike'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date']},
        ),
    ]
