# Generated by Django 4.0 on 2022-02-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_post_num_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='num_dislikes',
            field=models.IntegerField(default=0),
        ),
    ]
